# name of our action
name: 'Chromatic Deployment'
# the event that will trigger the action
on: push

# what the action will do
jobs:
  test:
    # the operating system it will run on
    runs-on: ubuntu-latest
    env:
      DEBUG: chromatic-cli
      NPM_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
      # version of @storybook/react in packages/ui
      # CHROMATIC_STORYBOOK_VERSION: 'react@6.0.0-rc.13'
    steps:
      - uses: actions/checkout@v1

      - name: Prepare repository
        run: |
          npm ci
          npx lerna bootstrap

      - name: Lint
        run: npm run lint

      - name: Build UI storybook
        working-directory: ./packages/ui
        run: npm run build-storybook
      - uses: chromaui/action@v1
        # options required to the GitHub chromatic action
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GH_TOKEN }}
          storybookBuildDir: ./packages/ui/build-sb

